services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
      - db
    env_file: .env.prod
    volumes:
      - ./:/api/
    networks:
      - network-cecr
  
  db:
    container_name: db
    image: postgres:12.19
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    networks:
      - network-cecr

  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    env_file: .env.prod
    command: "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --save 60 100"
    ports:
      - 6379:6379
    volumes:
      - ./docker/data/redis:/data
    networks:
      - network-cecr
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .env.prod
    volumes:
      - ./docker/data/rabbitmq:/var/lib/rabbitmq
    networks:
      - network-cecr

networks:
  network-cecr:
    driver: bridge