FROM elixir:1.16.2

ARG PHOENIX_VERSION=1.7.7

WORKDIR /api/

COPY . .

RUN mix local.hex --force
RUN mix archive.install --force hex phx_new ${PHOENIX_VERSION}
RUN mix local.rebar --force
RUN mix deps.get